name: Build WPF App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install .NET Framework 4.6.1 Developer Pack
        run: choco install netfx-4.6.1-devpack -y

      - name: Restore Dependencies
        run: msbuild app/Windows/Test/WpfApp1/WpfApp1.sln /t:Restore

      - name: Build Solution
        run: msbuild app/Windows/Test/WpfApp1/WpfApp1.sln /p:Configuration=Release

      - name: Publish Application
        run: msbuild app/Windows/Test/WpfApp1/WpfApp1.sln /p:Configuration=Release /p:DeployOnBuild=true /p:OutputPath=out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpf-app
          path: out
