name: Build WPF App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore app/Windows/Test/WpfApp1/WpfApp1.sln

      - name: Build Solution
        run: dotnet build app/Windows/Test/WpfApp1/WpfApp1.sln --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish app/Windows/Test/WpfApp1/WpfApp1.sln -c Release -o out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpf-app
          path: out
