name: Build XC8 Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install XC8 Compiler
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v3.00-full-install-linux-x64-installer.run -O xc8-installer.run
          chmod +x xc8-installer.run
          sudo ./xc8-installer.run --mode unattended --unattendedmodeui none --installdir /opt/microchip/xc8 --license accept
          echo "/opt/microchip/xc8/bin" >> $GITHUB_PATH

      - name: Compile with XC8 (Multiple .c Files)
        run: |
          xc8 --chip=18F2550 firmware_rs-485.x/*.c -o firmware_rs-485.x/output.hex

      - name: Upload HEX file
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: firmware_rs-485.x/output.hex
