name: Build XC8 Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install XC8 Compiler
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v3.00-full-install-linux-x64-installer.run -O xc8-installer.run
          chmod +x xc8-installer.run
          sudo ./xc8-installer.run --mode unattended --unattendedmodeui none --installdir /opt/microchip/xc8 --netservername localhost
          echo "/opt/microchip/xc8/bin" >> $GITHUB_PATH
          export PATH=$PATH:/opt/microchip/xc8/bin
          echo "Updated PATH: $PATH"

      - name: Check XC8 installation
        run: |
          ls /opt/microchip/xc8/bin
          which xc8-cc
          xc8-cc --version

      - name: Compile with XC8 (Multiple .c Files) firmware_rs-485.x
        run: |
          xc8-cc -mcpu=18F2550 --chip=18F2550 firmware_rs-485.x/*.c -o firmware_rs-485.x/output.hex

      - name: Compile with XC8 (Multiple .c Files) Firmware.X
        run: |
          xc8-cc -mcpu=18F2550 --chip=18F2550 Firmware.X/*.c -o Firmware.X/output.hex

      - name: Upload HEX file firmware_rs-485
        uses: actions/upload-artifact@v4
        with:
          name: firmware_rs-485
          path: firmware_rs-485.x/output.hex

      - name: Upload HEX file Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: Firmware.X/output.hex
