name: Build XC8 project firmware_rs-485
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project with MPLAB X IDE
        uses: aeraterta/mplab-xc8-action@1.0
        with:
          project: firmware_rs-485.x
          packs: "ATtiny_DFP=3.1.260"
          configuration: default
          mplabx-version: 6.20
          xc8-version: 2.50
