name: Build MPLAB X Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install MPLAB X and XC8
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/MPLABX-IDE/MPLABX-v5.40-linux-installer.tar 
          tar -xf MPLABX-v5.40-linux-installer.tar
          sudo ./MPLABX-v5.40-linux-installer.sh --mode unattended
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/XC-Compiler/xc8-v2.00-linux-installer.run
          chmod +x xc8-v2.00-linux-installer.run
          sudo ./xc8-v2.00-linux-installer.run --mode unattended

      - name: Build project
        run: |
          /opt/microchip/xc8/v2.00/bin/xc8-cc --project=firmware_rs-485.x --output=build/output.hex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: build/output.hex
