name: Build MPLAB X Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Install XC8 Compiler
        run: |
          XC8_URL="https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v2.50-full-install-linux-x64-installer.run"
          wget -q $XC8_URL -O xc8-installer.run
          chmod +x xc8-installer.run
          sudo ./xc8-installer.run --mode unattended --unattendedmodeui none --installdir /opt/microchip/xc8
          echo "/opt/microchip/xc8/bin" >> $GITHUB_PATH
      - name: Download the source code
        uses: actions/checkout@v1
      - name: Build
        uses: jeandeaual/mplabx-xc8-build-action@v0.2.0
        with:
          project: firmware_rs-485.x
          configuration: default
          xc8-version: "2.50"  # Sostituisci con la versione desiderata
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-output
          path: firmware_rs-485.X/dist/default/production/*.hex
